#!/bin/bash

# If no GPUs are specified, throw an error
if [ $# -eq 0 ]; then
    echo "No GPUs specified. Please provide the indices of the GPUs to tune the kernels for."
    exit 1
fi

available_gpus=$(nvidia-smi --query-gpu=index --format=csv,noheader | tr '\n' ' ')
for i in $@; do
    if [[ ! $available_gpus =~ (^|[[:space:]])$i($|[[:space:]]) ]]; then
        echo "GPU $i is not available. Please provide the indices of the GPUs to tune the kernels for."
        exit 1
    fi
done

# Set path of directory containing this script
DIR=$(dirname $0)

SOURCE_DIR=$DIR/..

BUILD_DIR=$SOURCE_DIR/build

TUNE_FILE=$SOURCE_DIR/utils/src/GPU_tunes.hpp

cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_KERNEL_TUNER=ON -S $SOURCE_DIR -B $BUILD_DIR
cmake --build $BUILD_DIR --target ecl_tune_kernels

# Command line args are the indices of the GPUs to tune the kernels for
for i in $@; do
    echo "Tuning kernels for GPU $i"
    # Tune the kernels for the specified GPU
    $BUILD_DIR/kernel_tuning/ecl_tune_kernels $DIR $i
    python $DIR/apply_tunes.py $TUNE_FILE
done

# Remove CSV files generated by the tuner
rm $DIR/*.csv